scrape_configs:
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /var/log/nginx/*.log

  - job_name: gunicorn
    static_configs:
      - targets:
          - localhost
        labels:
          job: gunicorn
          __path__: /var/log/gunicorn/*.log