name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract Git tag
      id: tag
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend/app
        platforms: linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ steps.tag.outputs.TAG }}
    
    - name: Update deployment version file
      run: echo "${{ steps.tag.outputs.TAG }}" > backend/app/deployment-version.txt

    - name: Create deployment version PR
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        commit-message: "chore: propose deployment of ${{ steps.tag.outputs.TAG }}"
        branch: deploy/${{ steps.tag.outputs.TAG }}
        title: "Deploy ${{ steps.tag.outputs.TAG }}"
        body: |
          🚀 New Docker image [${{ steps.tag.outputs.TAG }}] has been published.

          This PR proposes deploying this version to production.

          Merge to trigger deployment via the Deploy workflow.
        base: main
        add-paths: |
          backend/app/deployment-version.txt
        labels: |
          deploy
          needs-approval
        reviewers: |
          denisgulev