name: Deploy Static Site to S3

on:
  pull_request:
    paths:
      - 'frontend/static/**'

jobs:
  deploy-static:
    name: Deploy Static Site
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/static
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-south-1

      - name: Sync to S3
        run: aws s3 sync ./dist/ s3://${{ secrets.BUCKET_NAME }} --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.DISTRIBUTION_ID }} \
            --paths "/*"
