name: Terraform Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/infra/**'

env:
  TF_CLOUD_ORGANIZATION: "Terraform-bootcamp-aws"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "Frontend"
  CONFIG_DIRECTORY: "./"

jobs:
  terraform:
    if: contains(github.event.head_commit.message, '[infra]') && github.event_name == 'push'
    name: Terraform Workflow
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/infra
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      # Optional: Apply with manual approval (requires custom setup or separate workflow)
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve