name: Terraform Plan and Validate (Backend)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/infra/**'

permissions:
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan and Validate (Backend)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        
      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan